### ISSUE TITLE
Adding apache nifi

### ISSUE THREAD

**Issue by Drasrax** [TOSIT-IO/TDP#15]
Adding apache nifi would allow to have an ETL in the stack, sqoop being deprecated.
A retag of apache nifi TDP version is done at this URL: https://github.com/Linagora-BigData/nifi-TDP

We are working on the integration steps.
Code modifications will follow soon:
- Artifact (tar.gz) download URL in tdp-getting-started
- ansible playbooks in tdp-collection-extras

**Comment by leopaul36** [comment]
Hello @Drasrax,

Thanks for wanting to contribute to TDP !

I have checked the your NiFi fork and have some remarks:
- You commited the [pom.xml.versionsBackup](https://github.com/Linagora-BigData/nifi-TDP/blob/nifi-1.16-TDP/pom.xml.versionsBackup) files which we don't need. You should use `-DgenerateBackupPoms=false` with `mvn versions:set`.
- You should build and test NiFi against the TDP versions of Hadoop, Hive, Ranger and HBase.
- You should also add a `tdp` dir to the fork with informations about how to package / test / which tests are not passing and why, etc. Please find a good example of what @Nuttymoon did with Spark 3 [here](https://github.com/TOSIT-IO/spark/tree/branch-3.2-TDP/tdp).

Once we have all that, we'll create a `nifi` repo to the TOSIT-IO organization and integrate your playbooks to the TDP extra collection.

**Comment by jbonofre** [comment]
Thanks for the proposal. Give me some time to back to you with an update about that.

**Comment by jbonofre** [comment]
IMHO, the code changes should be discussed in the PR (not in the issue)

**Comment by leopaul36** [comment]
> IMHO, the code changes should be discussed in the PR (not in the issue)

Agreed! Thought it's a bit special here because we are talking about integrating their repo into the TOSIT-FR org.

I created an issue in their repo here: https://github.com/Linagora-BigData/nifi-TDP/issues/1

**Comment by rpignolet** [comment]
Close as inactive.
