### ISSUE TITLE
Enforce conventional commit

### ISSUE THREAD

**Issue by wdavidw** [TOSIT-IO/TDP#3]
[Conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) standardize commit message to provide "human and machine readable meaning to commit messages". Two obvious benefits are automatic versioning and changelog generation. Commit message headers looks like `<type>[optional scope]: <description>`, for example `docs(hdfs): list public ports`

It is achieved with the creation of a git `pre-commit` hook. Multiple approaches are possible to write and deploy the hook. The Node.js community provides a mature ecosystem, but introducing NPM related packages into TDP seems irrelevant. We could go the Python way, for example with [pre-commit](https://pre-commit.com/index.html) and [commitizen](https://github.com/commitizen-tools/commitizen) or with our own Python script, writing a custom hook is easy. Hooks are registered into the local git repository manually or automatically. Manual installation is a single command such as `pre-commit install --hook-type commit-msg` in the case of `pre-commit`. It needs to be well documented to be applied by everyone. Automatic registration declare a command to register the hook. It is integrated with the package manager. You can see an example [in the CSV parser](https://github.com/adaltas/node-csv/blob/master/package.json#L17) where `husky` is called to register the commit hook anytime a developer execute `npm install` which, in the Node.js ecosystem, is mandatory. Probably the same in Python could be achieved with [poetry](https://python-poetry.org).

Additionally, a [GitHub bot](https://github.com/apps/semantic-pull-requests) ensure the usage of conventional commit by any contributor (disclaimer, I didn't use it yet but I will soon, I certainly have a need for it in my projects).

**Comment by wdavidw** [comment]
Disagree, the GH action complements another tools, potentially with greater personalization such as a restrictive list of scopes. Citing the [GH action](https://github.com/webiny/action-conventional-commits) used in commit #22: 

> Note that, typically, you would make this check on a pre-commit hook (for example, using something like [Commitlint](https://commitlint.js.org/)), but those can easily be skipped, hence this GitHub action.

Reopening in case the discussion should be pursued toward a future implementation, feel free to close the issue if you believe GH action is good enough for a long time.

**Comment by leopaul36** [comment]
As stated in #22:

> The use of a linter such as [commitlint](https://github.com/conventional-changelog/commitlint) will be evaluated later once we are comfortable with our conventional commit patterns.

**Comment by rpignolet** [comment]
Done via github action for all repository. Done with `pre-commit` for `tdp-lib` and `tdp-server`.
