### ISSUE TITLE
Rollback mechanism

### ISSUE THREAD

**Issue by ChristopheLRTE** [TOSIT-IO/TDP#56]
Hello,

I wanted to know if had imagined a rollback mechanism after production and how it worked.

We found that during a TDP installation the configuration files were first stored in a `conf.xxxxxxx` directory (_where `xxxxxxx` seems to be a timestamp_).
Did you plan to use it for that ?

Are there other things planned in this way ?

Thank you and have a good day !
C.L.

**Comment by rpignolet** [comment]
Hi, directories `conf.xxxxxxx` are created each time playbook `*_config` are run in order to have a history but this feature is not use and will be removed in a future I think. Keeping track of configuration version is for `tdp-lib` en `tdp-server`. This is the purpose of `tdp_vars`.

**Comment by rpignolet** [comment]
Close as answered.
